### ISSUE TITLE
Add role requirement and Amari API / AmariBot.py integration to giveaway-plugin

### ISSUE THREAD

**Issue by stikhead** [Jerrie-Aries/modmail-plugins#20]
Hello,
I would like to request the following features for the giveaway-plugin:

･ Add a role requirement feature, so that only users with a certain role or exp are able to enter the giveaway.

･ Add integration with the Amari API or AmariBot.py , so that member's exp can be checked. Specifically, the plugin should use the Amari API or AmariBot.py to check the member's exp points when they try to enter the giveaway, and only allow entry if the member's exp matches the requirement.

Amari Bot is a popular leveling bot. It also have API, AmariBot.py and AmariBot.js libraries.
The Amari API has an endpoint for retrieving a user's exp points on a Discord server. By integrating with the Amari API or AmariBot.py , the plugin can use the member's exp points as an additional requirement for entering the giveaway, in addition to or instead of the role requirement.

I think these features would be a useful and unique addition to the plugin, and I believe they would be well received by the community.

- https://github.com/TheF1ng3r/amari.py
- https://amaripy.readthedocs.io/en/latest/ 
- https://docs.amaribot.com/api/api

Thank you for considering this request!

**Comment by Jerrie-Aries** [comment]
I will consider the role requirement feature as I was already planning to implement it anyways.

About the Amari API thing, I think it won't be added as it's kinda external feature and requires additional package and API requests.
