### ISSUE TITLE
Plugins not downloading

### ISSUE THREAD

**Issue by wantuh** [Jerrie-Aries/modmail-plugins#41]
I installed the extended utils, but whenever I try to install just the utils or anything else it tells me it is already installed yet I cannot find a page of the plugin in my help page.

**Comment by Jerrie-Aries** [comment]
You need to provide more basic information.

- Bot version
- Error logs
- Hosting method

And other helpful contexts if any.

**Comment by ravicant** [comment]
> You need to provide more basic information.
> 
>     * Bot version
> 
>     * Error logs
> 
>     * Hosting method
> 
> 
> And other helpful contexts if any.

can i get Your Discord ID Pls

**Comment by Jerrie-Aries** [comment]
> can i get Your Discord ID Pls 

`@jerrie_aries`

**Comment by ravicant** [comment]
> > can i get Your Discord ID Pls
> 
> `@jerrie_aries`

i have added you can you check
