### ISSUE TITLE
Plugin Refuses to install

### ISSUE THREAD

**Issue by csptechnologies** [Jerrie-Aries/modmail-plugins#43]
![image](https://github.com/user-attachments/assets/a1a78d6f-dc31-41d2-ad0b-afc296d2b1e2)
Plugin refuses to install and the bot says "Invalid Extension"

**Comment by Jerrie-Aries** [comment]
You need to install `utils` plugin first.

![IMG_20240719_203850.jpg](https://github.com/user-attachments/assets/ec7e35fa-5137-407a-80d7-d418d647508d)
