### ISSUE TITLE
Logviewer not working 

### ISSUE THREAD

**Issue by AvixWz** [Jerrie-Aries/modmail-plugins#44]
![Screenshot_2024-10-12-06-54-14-90_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/06f036bc-d0d5-4ad6-806a-a4b112975fa0)

**Comment by Jerrie-Aries** [comment]
Does your bot have icon/pfp set?

**Comment by AvixWz** [comment]
Yeah it's working now.but where I can get host or cause I only have port?
